name: flutter_map_animations
description: Animation utilities for markers and controls of the flutter_map package.
version: 0.5.0
homepage: https://github.com/TesteurManiak/flutter_map_animations
repository: https://github.com/TesteurManiak/flutter_map_animations
issue_tracker: https://github.com/TesteurManiak/flutter_map_animations/issues
topics:
  - flutter-map
  - map
  - animation

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  latlong2: ^0.9.0

dev_dependencies:
  custom_lint: ^0.5.3
  fd_lints: ^2.2.0
  flutter_test:
    sdk: flutter
