name: Sanity Check

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
            - dev
    workflow_dispatch:

concurrency:
    group: ${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    sanity_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - uses: subosito/flutter-action@v2.14.0

            - name: Analyze project
              run: flutter analyze --no-fatal-infos

            - name: Run tests
              run: flutter test